name: CI
run-name: Build Vite Application
on: [push]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Create .env file from secret
        run: echo "${{ secrets.APP_ENV }}" > .env
        
      - name: Update config
        run: |
          git config --global user.email "csperando@gmail.com"
          git config --global user.name "Coleman Sperando"

      - name: Build dist/ directory
        run: |
          echo "${{  github.repository }} cloned"
          npm install
          npm run build

      - name: Force commit updated dist
        run: |
          git add dist -f
          git commit -m "actions automated commit build dist/"

      - name: Check if gh-pages exists
        id: exists
        run: |
          echo "EXISTS"=`git ls-remote origin gh-pages` >> $GITHUB_OUTPUT

      - name: Push to subtree
        if: ${{ steps.exists.outputs.EXISTS }}
        run: |
          echo "Pushing changes to existing branch."
          git push origin `git subtree split --prefix=dist/ main`:gh-pages --force

      - name: Create gh-pages branch
        if: ${{ !steps.exists.outputs.EXISTS }}
        run: |
          echo "The branch gh-pages does not exist. Creating initial subtree from dist/."
          git subtree push --prefix dist/ origin gh-pages
